#!/usr/bin/env bash
# Runs ON the bastion, after scenario17-keycloak-up.sh AND after
# `./harness.sh maas-up` (needs the MaaS AuthPolicy to already exist).
# Adds Keycloak as a trusted external JWT identity source on
# the MaaS gateway's AuthPolicy, alongside the existing api-keys and
# openshift-identities (oc token) sources -- idempotent, safe to re-run.
#
# Why this is a separate step and not baked into the AuthPolicy from the
# start: this AuthPolicy is owned/regenerated by maas-controller, so this
# patch can be wiped out by that controller's own reconciliation (observed
# live -- see docs/scenarios/17-maas-external-oidc-auth.md section 7 in
# openshift-ai-maas-demo). Re-run this script any time `keycloak-identities`
# seems to have disappeared from the policy (e.g. after creating/deleting a
# MaaSAuthPolicy/MaaSSubscription, which triggers a maas-controller resync).
set -euo pipefail
export KUBECONFIG="$HOME/ocp-install/auth/kubeconfig"

: "${KEYCLOAK_NAMESPACE:?set KEYCLOAK_NAMESPACE}"
: "${KEYCLOAK_REALM:?set KEYCLOAK_REALM}"

CLUSTER_DOMAIN=$(oc get ingresses.config.openshift.io cluster -o jsonpath='{.spec.domain}')
ISSUER_URL="https://maas-keycloak.${CLUSTER_DOMAIN}/realms/${KEYCLOAK_REALM}"

current=$(oc get authpolicy maas-gateway-auth -n openshift-ingress \
  -o jsonpath='{.spec.defaults.rules.authentication.keycloak-identities.jwt.issuerUrl}' 2>/dev/null || true)

if [ "$current" = "$ISSUER_URL" ]; then
  echo "keycloak-identities already wired with the correct issuerUrl."
else
  [ -n "$current" ] && echo "keycloak-identities present but stale (issuerUrl='$current') -- overwriting."
  oc patch authpolicy maas-gateway-auth -n openshift-ingress --type=merge -p "{
    \"spec\": {\"defaults\": {\"rules\": {\"authentication\": {
      \"keycloak-identities\": {
        \"priority\": 2,
        \"when\": [{\"predicate\": \"!request.headers.authorization.startsWith(\\\"Bearer sk-oai-\\\")\"}],
        \"jwt\": {\"issuerUrl\": \"${ISSUER_URL}\"}
      }
    }}}}
  }"
  echo "Wired keycloak-identities -> ${ISSUER_URL}"
fi

echo ""
echo "Verify: oc get authpolicy maas-gateway-auth -n openshift-ingress -o jsonpath='{.status.conditions[-1]}'"
echo "Should say Enforced=True. If it says Overridden, a competing AuthPolicy exists on"
echo "maas-default-gateway -- check that maas-up.sh Step 4"
echo "(opendatahub.io/managed=false annotation) ran successfully."
